set timing on

drop table eloc_part;

create table eloc_part (
 AREA_ID				            NUMBER,
 AREA_NAME					    VARCHAR2(64 CHAR),
 KEY						    VARCHAR2(4000),
 ALIASES					    VARCHAR2(4000),
 LANG_CODE					    VARCHAR2(3),
 ADMIN_LEVEL					    NUMBER,
 LEVEL1_AREA_ID 				    NUMBER,
 LEVEL2_AREA_ID 				    NUMBER,
 LEVEL3_AREA_ID 				    NUMBER,
 LEVEL4_AREA_ID 				    NUMBER,
 LEVEL5_AREA_ID 				    NUMBER,
 LEVEL6_AREA_ID 				    NUMBER,
 LEVEL7_AREA_ID 				    NUMBER,
 CENTER_LONG					    NUMBER,
 CENTER_LAT					    NUMBER,
 POSTAL_CODE					    VARCHAR2(16 CHAR),
 COUNTRY_CODE_2 				    VARCHAR2(2),
 REAL_NAME					    VARCHAR2(64 CHAR),
 GOVERNMENT_CODE				    VARCHAR2(50 CHAR),
 ALIAS_LIST					    VARCHAR2(4000),
 LANG_ID					    NUMBER
)
partition by range (lang_id)
 ( partition p0 values less than (1), 
   partition p1 values less than (2),
   partition p2 values less than (3), 
   partition p3 values less than (4),
   partition p4 values less than (5),
   partition p5 values less than (6),
   partition p6 values less than (7),
   partition p7 values less than (8),
   partition p8 values less than (9),
   partition p9 values less than (10),
   partition p10 values less than (11),
   partition p11 values less than (12),
   partition p12 values less than (13),
   partition p13 values less than (14),
   partition p14 values less than (15),
   partition p15 values less than (16),
   partition p16 values less than (17),
   partition p17 values less than (18),
   partition p18 values less than (19),
   partition p19 values less than (20),
   partition p20 values less than (21),
   partition p21 values less than (22),
   partition p22 values less than (23),
   partition p23 values less than (24),
   partition p24 values less than (25),
   partition p25 values less than (26),
   partition p26 values less than (27),
   partition p27 values less than (28),
   partition p28 values less than (29),
   partition p29 values less than (30),
   partition p30 values less than (31),
   partition p31 values less than (32),
   partition p32 values less than (33),
   partition p33 values less than (34),
   partition p34 values less than (35),
   partition p35 values less than (36),
   partition p36 values less than (37),
   partition p37 values less than (38),
   partition p38 values less than (39),
   partition p39 values less than (40),
   partition p40 values less than (41),
   partition p41 values less than (42),
   partition p42 values less than (43),
   partition p43 values less than (44),
   partition p44 values less than (45),
   partition p45 values less than (46),
   partition p46 values less than (47),
   partition p47 values less than (48),
   partition p48 values less than (49),
   partition p49 values less than (50),
   partition p50 values less than (51),
   partition p51 values less than (52),
   partition p52 values less than (53),
   partition p53 values less than (54),
   partition p54 values less than (55),
   partition p55 values less than (56),
   partition p56 values less than (57),
   partition p57 values less than (58),
   partition p58 values less than (59),
   partition p59 values less than (60)
 );


-- first insert all the data without aliases

insert into eloc_part (
 AREA_ID,
 AREA_NAME,
 KEY,
 ALIASES,
 LANG_CODE,
 ADMIN_LEVEL,
 LEVEL1_AREA_ID,
 LEVEL2_AREA_ID,
 LEVEL3_AREA_ID,
 LEVEL4_AREA_ID,
 LEVEL5_AREA_ID,
 LEVEL6_AREA_ID,
 LEVEL7_AREA_ID,
 CENTER_LONG,
 CENTER_LAT,
 POSTAL_CODE,
 COUNTRY_CODE_2,
 REAL_NAME,
 GOVERNMENT_CODE,
 ALIAS_LIST,
 LANG_ID
) 
select 
 AREA_ID,
 AREA_NAME,
 KEY,
 null,
 LANG_CODE,
 ADMIN_LEVEL,
 LEVEL1_AREA_ID,
 LEVEL2_AREA_ID,
 LEVEL3_AREA_ID,
 LEVEL4_AREA_ID,
 LEVEL5_AREA_ID,
 LEVEL6_AREA_ID,
 LEVEL7_AREA_ID,
 CENTER_LONG,
 CENTER_LAT,
 POSTAL_CODE,
 COUNTRY_CODE_2,
 REAL_NAME,
 GOVERNMENT_CODE,
 ALIAS_LIST,
 0
from eloc_work;

    
