-- liquibase formatted sql

-- changeset liquibase:1
CREATE USER "SCHEMA_A" NO AUTHENTICATION;
ALTER USER "SCHEMA_A" GRANT CONNECT THROUGH SYSTEM;
GRANT UNLIMITED TABLESPACE TO "SCHEMA_A";
GRANT CONNECT, RESOURCE TO "SCHEMA_A";
ALTER USER "SCHEMA_A" DEFAULT ROLE CONNECT, RESOURCE;