SQL> select ctx_report.describe_index(index_name=>'i', report_format=>'XML') from dual;
<CTXREPORT>
<DESCRIBE_INDEX>
<INDEX_ATTRIBUTES>
<INDEX_ATTRIBUTE NAME="index name">&quot;ROGER&quot;.&quot;I&quot;</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="index id">1340</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="index type">context</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="base table">&quot;ROGER&quot;.&quot;T&quot;</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="primary key column"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="text column">C</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="text column type">VARCHAR2(2000)</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="language column"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="format column"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="charset column"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="configuration column"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="Query Stats Enabled">NO</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="status">INDEXED</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="full optimize token"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="full optimize count"></INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="docid count">0</INDEX_ATTRIBUTE>
<INDEX_ATTRIBUTE NAME="nextid">1</INDEX_ATTRIBUTE>
</INDEX_ATTRIBUTES>
<INDEX_OBJECTS>
<INDEX_OBJECT CLASS="datastore" OBJECT="DIRECT_DATASTORE">
</INDEX_OBJECT>
<INDEX_OBJECT CLASS="filter" OBJECT="NULL_FILTER">
</INDEX_OBJECT>
<INDEX_OBJECT CLASS="section group" OBJECT="NULL_SECTION_GROUP">
</INDEX_OBJECT>
<INDEX_OBJECT CLASS="lexer" OBJECT="BASIC_LEXER">
</INDEX_OBJECT>
<INDEX_OBJECT CLASS="wordlist" OBJECT="BASIC_WORDLIST">
<INDEX_OBJECT_ATTRIBUTE NAME="stemmer">ENGLISH</INDEX_OBJECT_ATTRIBUTE>
<INDEX_OBJECT_ATTRIBUTE NAME="fuzzy_match">GENERIC</INDEX_OBJECT_ATTRIBUTE>
</INDEX_OBJECT>
<INDEX_OBJECT CLASS="stoplist" OBJECT="BASIC_STOPLIST">
<INDEX_STOP STOP_TYPE="STOP_WORD">Mr</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">Mrs</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">Ms</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">a</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">all</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">almost</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">also</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">although</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">an</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">and</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">any</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">are</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">as</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">at</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">be</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">because</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">been</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">both</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">but</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">by</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">can</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">could</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">d</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">did</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">do</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">does</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">either</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">for</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">from</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">had</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">has</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">have</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">having</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">he</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">her</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">here</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">hers</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">him</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">his</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">how</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">however</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">i</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">if</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">in</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">into</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">is</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">it</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">its</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">just</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">ll</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">me</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">might</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">my</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">no</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">non</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">nor</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">not</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">of</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">on</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">one</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">only</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">onto</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">or</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">our</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">ours</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">s</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">shall</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">she</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">should</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">since</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">so</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">some</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">still</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">such</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">t</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">than</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">that</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">the</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">their</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">them</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">then</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">there</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">therefore</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">these</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">they</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">this</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">those</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">though</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">through</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">thus</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">to</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">too</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">until</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">ve</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">very</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">was</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">we</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">were</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">what</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">when</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">where</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">whether</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">which</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">while</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">who</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">whose</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">why</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">will</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">with</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">would</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">yet</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">you</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">your</INDEX_STOP>
<INDEX_STOP STOP_TYPE="STOP_WORD">yours</INDEX_STOP>
</INDEX_OBJECT>
<INDEX_OBJECT CLASS="storage" OBJECT="BASIC_STORAGE">
<INDEX_OBJECT_ATTRIBUTE NAME="i_table_clause">tablespace sysaux</INDEX_OBJECT_ATTRIBUTE>
<INDEX_OBJECT_ATTRIBUTE NAME="r_table_clause">lob(data) store as (nocache)</INDEX_OBJECT_ATTRIBUTE>
<INDEX_OBJECT_ATTRIBUTE NAME="i_index_clause">compress 2</INDEX_OBJECT_ATTRIBUTE>
<INDEX_OBJECT_ATTRIBUTE NAME="stage_itab">YES</INDEX_OBJECT_ATTRIBUTE>
</INDEX_OBJECT>
</INDEX_OBJECTS>
</DESCRIBE_INDEX>
</CTXREPORT>


SQL> spool off
