micronaut:
  application:
    name: OracleJsonDemo
  server:
    thread-selection: io
datasources:
  default:
    schema-generate: none
    packages: org.com.example.entity
    dialect: oracle
test-resources:
  containers:
    oracle:
      image-name: gvenzl/oracle-free:latest-faststart
      startup-timeout: 360s
      db-name: test
flyway:
  datasources:
    default:
      enabled: true
      baseline-version: 0
      baseline-on-migrate: true