BEGIN
  FOR REC IN (SELECT name FROM DBA_SQL_PROFILES WHERE sql_text LIKE '%PROFTEST%')
  LOOP
      DBMS_SQLTUNE.DROP_SQL_PROFILE ( name => rec.name);
  END LOOP;
END;
/

DECLARE
  l_plans_dropped  PLS_INTEGER;
BEGIN
  FOR REC IN (SELECT DISTINCT SQL_HANDLE FROM DBA_SQL_PLAN_BASELINES WHERE sql_text LIKE '%PROFTEST%')
  LOOP
      L_PLANS_DROPPED := DBMS_SPM.DROP_SQL_PLAN_BASELINE (
        sql_handle => rec.sql_handle,
        PLAN_NAME  => NULL);
  END LOOP;
END;
/
