CREATE USER test_user IDENTIFIED BY test_password;
GRANT CREATE SESSION TO test_user;
GRANT CREATE TABLE TO test_user;
GRANT CREATE SEQUENCE TO test_user;
GRANT DROP ANY TABLE TO test_user;
GRANT UNLIMITED TABLESPACE TO test_user;