CREATE USER RSIATP_USER IDENTIFIED BY "<PASSWORD>";
GRANT DWROLE TO RSIATP_USER;
GRANT UNLIMITED TABLESPACE TO RSIATP_USER;

CREATE TABLE RSIATP_USER.CUSTOMERS (
 ID NUMBER(20,0),
 NAME VARCHAR2(20 BYTE),
 REGION VARCHAR2(20 BYTE)
);
