spring.jpa.database=default
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

spring.main.web-application-type=servlet
server.port=8080
logging.level.org.springframework.boot.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
#logging.level.oracle.ucp=TRACE
#logging.level.oracle.jdbc=TRACE
#logging.level.oracle.net=TRACE
#logging.level.writeDataSource=TRACE
#logging.level.readDataSource=TRACE
#logging.level.catalogDataSource=TRACE
#logging.level.ShardDemoPool=TRACE
#logging.level.shardDemoDataSource=TRACE

# disable actuator health check, can not use db connection without sharding key
management.health.db.enabled=false
# management.endpoint.health.show-details=always

#logging.level.org.hibernate=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#logging.level.org.springframework.boot.context.properties=DEBUG
#debug=true

# Set the default log level for the application
#logging.level.root=TRACE
# Set specific log levels for packages
#logging.level.com.foobar=TRACE
#logging.level.org.springframework=TRACE
#spring.output.ansi.enabled=always
#logging.level.org.springframework.transaction=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG

#java.util.logging.ConsoleHandler.level = ALL

#spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
#spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT

# Oracle DB - "read"
#catalog.datasource.url=jdbc:oracle:thin:@PCATALOG?TNS_ADMIN=/root/
catalog.datasource.url=jdbc:oracle:thin:@//gsm-shard-emea:1521/pcatalog
catalog.datasource.username=app_schema
catalog.datasource.password=AcrorA123456__

# Oracle DB - "read"
#read.datasource.url=jdbc:oracle:thin:@RO?TNS_ADMIN=/root/
read.datasource.url=jdbc:oracle:thin:@//gsm-emea:1521/ro_service.orasdb.oradbcloud
read.datasource.username=app_schema
read.datasource.password=AcrorA123456__

# Oracle DB - "write"
#write.datasource.url=jdbc:oracle:thin:@RW?TNS_ADMIN=/root/
write.datasource.url=jdbc:oracle:thin:@//gsm-emea:1521/rw_service.orasdb.oradbcloud
write.datasource.username=app_schema
write.datasource.password=AcrorA123456__
