# Code Sample from the tutorial at https://learncodeshare.net/2015/07/09/delete-crud-using-cx_oracle/
#  section titled "Resetting the data"
# The following resets the data for use with the update section
# For both tables:
#  Table data is removed.
#  The identity column is set to start with the id after the starting data.
#  Using the executemany function an array of starting data is inserted into the table.

import cx_Oracle
import os
connectString = os.getenv('DB_CONNECT') # The environment variable for the connect string: DB_CONNECT=user/password@database
con = cx_Oracle.connect(connectString)
cur = con.cursor()

# Delete rows
statement = 'delete from lcs_pets'
cur.execute(statement)

# Reset Identity Coulmn
statement = 'alter table lcs_pets modify id generated BY DEFAULT as identity (START WITH 8)'
cur.execute(statement)

# Delete rows
statement = 'delete from lcs_people'
cur.execute(statement)

# Reset Identity Coulmn
statement = 'alter table lcs_people modify id generated BY DEFAULT as identity (START WITH 8)'
cur.execute(statement)

# Insert default rows
rows = [{'id':1, 'name':'Bob', 'age':35, 'notes':'I like dogs'},
        {'id':2, 'name':'Kim', 'age':27, 'notes':'I like birds'},
        {'id':3, 'name':'Cheryl', 'age':23, 'notes':'I like horses'},
        {'id':4, 'name':'Bob', 'age':27, 'notes':'I like rabbits'},
        {'id':5, 'name':'Stacey', 'age':45, 'notes':'I like snakes'},
        {'id':6, 'name':'Pete', 'age':23, 'notes':'I like cats'},
        {'id':7, 'name':'Pat', 'age':36, 'notes':'I like dogs'}]
cur.bindarraysize = 2
cur.executemany("insert into lcs_people(id, name, age, notes) values (:id, :name, :age, :notes)", rows)
con.commit()

# Insert default rows
rows = [{'id':1, 'name':'Duke', 'owner':1, 'type':'dog'},
        {'id':2, 'name':'Dragon', 'owner':2, 'type':'bird'},
        {'id':3, 'name':'Sneaky', 'owner':5, 'type':'snake'},
        {'id':4, 'name':'Red', 'owner':2, 'type':'bird'},
        {'id':5, 'name':'Red', 'owner':3, 'type':'horse'},
        {'id':6, 'name':'Buster', 'owner':1, 'type':'dog'},
        {'id':7, 'name':'Fido', 'owner':7, 'type':'cat'}]
cur.bindarraysize = 2
cur.executemany("insert into lcs_pets (id, name, owner, type) values (:id, :name, :owner, :type)", rows)
con.commit()

cur.close()
