SET ECHO OFF

PROMPT Disabling automated snapshot carousel for &&MAIN_PDB

ALTER SESSION SET CONTAINER = &&MAIN_PDB;
ALTER PLUGGABLE DATABASE SNAPSHOT MODE MANUAL;
ALTER SESSION SET CONTAINER = &&ROOT_CONTAINER;
