SET ECHO OFF

PROMPT Dropping snapshot &&DROP_SNAPSHOT_NAME from &&MAIN_PDB

WHENEVER SQLERROR CONTINUE

ALTER SESSION SET CONTAINER = &&MAIN_PDB;
ALTER PLUGGABLE DATABASE DROP SNAPSHOT &&DROP_SNAPSHOT_NAME;
ALTER SESSION SET CONTAINER = &&ROOT_CONTAINER;

WHENEVER SQLERROR EXIT SQL.SQLCODE
