{
 "title": "Cell Disk",
 "tags": [
  "celldisk",
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "CL_CPUT" } },
   {
    "name": "pod",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\"}"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"}"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "deviceType",
    "query": {
     "query": "{__name__=~\"CD_IO_RQ_R_SM_SEC|CD_IO_RQ_W_SM_SEC|CD_IO_RQ_R_LG_SEC|CD_IO_RQ_W_LG_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName!~\"PM_.*\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "$deviceType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deviceType" },
  {
   "title": "Small Reads Requests",
   "type": "timeseries",
   "description": "EXAREL: Small read requests on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_RQ_R_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Small Write Requests",
   "type": "timeseries",
   "description": "EXAREL: Small write requests on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_RQ_W_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Large Read Requests",
   "type": "timeseries",
   "description": "EXAREL: Large read requests on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_RQ_R_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Large Write Requests",
   "type": "timeseries",
   "description": "EXAREL: Large write requests on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_RQ_W_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Small Read MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Small read MIB/s on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_BY_R_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Smalll Write MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Small write MiB/s on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_BY_W_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Large Read MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Large read MiB/s on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_BY_R_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Large Write MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Large write MiB/s on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_BY_W_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Small Read Latency",
   "type": "timeseries",
   "description": "EXAREL: Average small read latency on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_TM_R_SM_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Small Write Latency",
   "type": "timeseries",
   "description": "EXAREL: Average small write latency on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_TM_W_SM_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Large Read Latency",
   "type": "timeseries",
   "description": "EXAREL: Average large read latency on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_TM_R_LG_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Large Write Latency",
   "type": "timeseries",
   "description": "EXAREL: Average large write latency on devices\nFD: flash\nCD: hard disk",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CD_IO_TM_W_LG_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  { "title": "Scrub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Scrub Requests",
   "type": "timeseries",
   "description": "EXAREL: Scrub IO requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "CD_IO_RQ_R_SCRUB_SEC{objectName=~\"CD_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "Scrub MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Scrub IO MiB/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "CD_IO_BY_R_SCRUB_SEC{objectName=~\"CD_.*\",server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  }
 ]
}