{
 "title": "Compute Server",
 "tags": [
  "compute",
  "server",
  "exadata",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "DS_CPUT" } },
   {
    "name": "pod",
    "query": {
     "query": "DS_CPUT{fleet=\"$fleet\"}"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "DS_CPUT{fleet=\"$fleet\",pod=\"$pod\"}"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "DS_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "EXAREL: CPU utilization",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DS_CPUT{server=~\"$server\"}",
     "legendFormat": "%CPU-{{server}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "EXAREL: Memory Utilization",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "DS_MEMUT{server=~\"$server\"}",
     "legendFormat": "%Used-{{server}}"
    },
    {
     "expr": "DS_MEMUT_MS{server=~\"$server\"}",
     "legendFormat": "%MS-{{server}}"
    }
   ]
  },
  {
   "title": "RX Bytes - Client Network",
   "type": "timeseries",
   "description": "EXAREL: RX bytes/s on client Network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "OS_NET_RX_BY_SEC{server=~\"$server\",objectName=~\".*eth.*\"}",
     "legendFormat": "{{objectName}}-{{server}}"
    }
   ]
  },
  {
   "title": "RX Bytes - RDMA",
   "type": "timeseries",
   "description": "EXAREL: Network throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(server) (EXW_ROCE_TX_BY_SEC{server=~\"$server\"})",
     "legendFormat": "{{server}}-RoCE"
    },
    {
     "expr": "sum by(server) (N_IB_MB_RCV_SEC{server=~\"$server\"})",
     "legendFormat": "{{server}}-IB"
    }
   ]
  },
  {
   "title": "TX Bytes - Client Network",
   "type": "timeseries",
   "description": "EXAREL: Tx bytes/s per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "OS_NET_TX_BY_SEC{server=~\"$server\",objectName=~\".*eth.*\"}",
     "legendFormat": "{{objectName}}-{{server}}"
    }
   ]
  },
  {
   "title": "TX Bytes - RDMA",
   "type": "timeseries",
   "description": "EXAREL: TX bytes on RDMA per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "sum by (server) (EXW_ROCE_TX_BY_SEC{server=~\"$server\"})",
     "legendFormat": "{{server}}-RoCE"
    },
    {
     "expr": "sum by (server) (N_IB_MB_TRANS_SEC{server=~\"$server\"})",
     "legendFormat": "{{server}}-IB"
    }
   ]
  },
  {
   "title": "RDS Ping (Lane 0)",
   "type": "timeseries",
   "description": "EXAREL: rds-ping on lane 0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_RDS_PING_0{server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  }
 ]
}