{
 "title": "Exadata Cluster",
 "tags": [
  "cluster",
  "exadata",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "fleet",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\"}"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\",fleet=\"$fleet\"}"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\",fleet=\"$fleet\",pod=\"$pod\"}"
    }
   },
   { "name": "filter" },
   { "name": "linkComputeDetails", "query": "${VAR_LINKCOMPUTEDETAILS}" },
   { "name": "linkCellDetails", "query": "${VAR_LINKCELLDETAILS}" },
   {
    "name": "deviceType",
    "query": {
     "query": "{__name__=~\"CD_IO_RQ_R_SM_SEC|CD_IO_RQ_W_SM_SEC|CD_IO_RQ_R_LG_SEC|CD_IO_RQ_W_LG_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName!~\"PM_.*\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Compute Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization (compute)",
   "type": "timeseries",
   "description": "EXAREL: CPU utilization on compute servers",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DS_CPUT{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}",
     "legendFormat": "{{server}}-{{nodeType}}"
    }
   ]
  },
  {
   "title": "Client Network",
   "type": "timeseries",
   "description": "EXAREL: Aggregated traffic on bondeth",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "sum by (server) (OS_NET_RX_BY_SEC{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName=~\"bondeth.*\"})",
     "legendFormat": "rx/s-{{server}}"
    },
    {
     "expr": "sum by (server) (OS_NET_TX_BY_SEC{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName=~\"bondeth.*\"})",
     "legendFormat": "tx/s-{{server}}"
    }
   ]
  },
  {
   "title": "RDMA Network",
   "type": "timeseries",
   "description": "EXAREL: Aggregated network traffic on storage interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "sum by (server) (N_IB_MB_RCV_SEC{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"})",
     "legendFormat": "rx/s-{{server}}-IB"
    },
    {
     "expr": "sum by (server) (N_IB_MB_TRANS_SEC{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"})",
     "legendFormat": "tx/s-{{server}}-IB"
    },
    {
     "expr": "sum by (server) (EXW_ROCE_RX_BY_SEC{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName=~\".*re.*|mlx.*\"})",
     "legendFormat": "rx/s-{{server}}-RoCE"
    },
    {
     "expr": "sum by (server) (EXW_ROCE_TX_BY_SEC{nodeType!=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName=~\".*re.*|mlx.*\"})",
     "legendFormat": "tx/s-{{server}}-RoCE"
    }
   ]
  },
  { "title": "CPU Utilization (Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "EXAREL: CPU utilization on storage servers",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "CL_CPUT{nodeType=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "IOPS - $deviceType",
   "type": "timeseries",
   "description": "EXAREL: IO requests on $deviceType\nFD: Flash\nCD: Hard Disk",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "repeat": "deviceType",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "sum by (server) ({__name__=~\"CD_IO_RQ_R_SM_SEC|CD_IO_RQ_W_SM_SEC|CD_IO_RQ_R_LG_SEC|CD_IO_RQ_W_LG_SEC\",nodeType=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName=~\"${deviceType}_.*\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "MiB/s - $deviceType",
   "type": "timeseries",
   "description": "EXAREL: IO MiB/s on $deviceType\nFD: Flash\nCD: Hard Disk",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "repeat": "deviceType",
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": " sum by (server) ({__name__=~\"CD_IO_BY_R_SM_SEC|CD_IO_BY_W_SM_SEC|CD_IO_BY_R_LG_SEC|CD_IO_BY_W_LG_SEC\", objectName=~\"${deviceType}_.*\",nodeType=\"STORAGE\", fleet=\"$fleet\", pod=\"$pod\", cluster=~\"$cluster\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Small Read Latency - $deviceType",
   "type": "timeseries",
   "description": "EXAREL: Average small read latency on $deviceType\nFD: Flash\nCD: Hard Disk",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "repeat": "deviceType",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "avg by (server) (CD_IO_TM_R_SM_RQ{nodeType=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\", cluster=~\"$cluster\",objectName=~\"${deviceType}_.*\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Large Read Latency - $deviceType",
   "type": "timeseries",
   "description": "EXAREL: Average large read latency on $deviceType\nFD: Flash\nCD: Hard Disk",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "repeat": "deviceType",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "avg by (server) (CD_IO_TM_R_LG_RQ{nodeType=\"STORAGE\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName=~\"${deviceType}_.*\"})",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}