{
 "title": "Flash Cache",
 "tags": [
  "flashcache",
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "CL_CPUT" } },
   {
    "name": "pod",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\"}"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"}"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Space Uitlization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Space Utilization",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache space utilization",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "FC_BY_ALLOCATED{server=~\"$server\"}",
     "legendFormat": "Allocated-{{server}}"
    },
    {
     "expr": "FC_BY_ALLOCATED_OLTP{server=~\"$server\"}",
     "legendFormat": "OLTP-{{server}}"
    },
    {
     "expr": "FC_COL_BY_USED{server=~\"$server\"}",
     "legendFormat": "CC-{{server}}"
    },
    {
     "expr": "FC_BYKEEP_OLTP{server=~\"$server\"}",
     "legendFormat": "KEEP-{{server}}"
    }
   ]
  },
  { "title": "Flash Cache IO Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Flash Cache Hit%",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache Hit percentage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "100*FC_IO_RQ_R_SEC{server=~\"$server\"}/(FC_IO_RQ_R_SEC{server=~\"$server\"}+FC_IO_RQ_R_MISS_SEC{server=~\"$server\"})",
     "legendFormat": "%OLTP Hit-{{server}}"
    },
    {
     "expr": "100*FC_IO_BY_R_SEC{server=~\"$server\"}/FC_IO_BY_R_SEC{server=~\"$server\"}+FC_IO_BY_R_MISS_DW_SEC{server=\"$server\"}",
     "legendFormat": "%Scan Hit-{{server}}"
    },
    {
     "expr": "100*FC_COL_IO_RQ_R_SEC{server=~\"$server\"}/FC_COL_IO_BY_R_ELIGIBLE_SEC{server=~\"$server\"}",
     "legendFormat": "%CC Hit-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache User Read Requests",
   "type": "timeseries",
   "description": "EXAREL: Flash cache user read requests",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "FC_IO_RQ_R_SEC{server=~\"$server\"}",
     "legendFormat": "OLTP Hits-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_R_MISS_SEC{server=~\"$server\"}",
     "legendFormat": "OLTP Misses-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_R_SKIP_SEC{server=~\"$server\"}",
     "legendFormat": "Skips-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_R_DW_SEC{server=~\"$server\"}",
     "legendFormat": "Scan Hits-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_R_MISS_DW_SEC{server=~\"$server\"}",
     "legendFormat": "Scan Misses-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache User Write Requests",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache user write requests",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "FC_IO_RQ_W_SEC{server=~\"$server\"}",
     "legendFormat": "Writes-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_W_FIRST_SEC{server=~\"$server\"}",
     "legendFormat": "First Writes-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_W_OVERWRITE_SEC{server=~\"$server\"}",
     "legendFormat": "Overwrites-{{$server}}"
    }
   ]
  },
  {
   "title": "Flash Cache Disk Writer Requests",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache disk writer IO requests",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "FC_IO_RQ_W_DISK_WRITER_SEC{server=~\"$server\"}",
     "legendFormat": "Writes-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_R_DISK_WRITER_SEC{server=~\"$server\"}",
     "legendFormat": "Reads-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache Internal Write Requests",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache internal write requests",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "FC_IO_RQ_W_POPULATE_SEC{server=~\"$server\"}",
     "legendFormat": "Population-{{server}}"
    },
    {
     "expr": "FC_IO_RQ_W_METADATA_SEC{server=~\"$server\"}",
     "legendFormat": "Metadata-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache User Read MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache user read MiB/s",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "FC_IO_BY_R_SEC{server=~\"$server\"}",
     "legendFormat": "OLTP Hits-{{server}}"
    },
    {
     "expr": "FC_IO_BY_R_MISS_SEC{server=~\"$server\"}",
     "legendFormat": "OLTP Misses-{{server}}"
    },
    {
     "expr": "FC_IO_BY_R_DW_SEC{server=~\"$server\"}",
     "legendFormat": "Scan Hits-{{server}}"
    },
    {
     "expr": "FC_IO_BY_R_MISS_DW_SEC{server=~\"$server\"}",
     "legendFormat": "Scan Misses-{{server}}"
    },
    {
     "expr": "FC_IO_BY_R_SKIP_SEC{server=~\"$server\"}",
     "legendFormat": "Skips-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache User Writes MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache user write MiB/s",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "FC_IO_BY_W_SEC{server=~\"$server\"}",
     "legendFormat": "Writes-{{server}}"
    },
    {
     "expr": "FC_IO_BY_W_FIRST_SEC{server=~\"$server\"}",
     "legendFormat": "First Writes-{{server}}"
    },
    {
     "expr": "FC_IO_BY_W_OVERWRITE_SEC{server=~\"$server\"}",
     "legendFormat": "Overwrites-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache Disk Writer MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache disk writer IO MiB/s",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "FC_IO_BY_W_DISK_WRITER_SEC{server=~\"$server\"}",
     "legendFormat": "Writes-{{server}}"
    },
    {
     "expr": "FC_IO_BY_R_DISK_WRITER_SEC{server=~\"$server\"}",
     "legendFormat": "Reads-{{server}}"
    }
   ]
  },
  {
   "title": "Flash Cache Internal Write MiB/s",
   "type": "timeseries",
   "description": "EXAREL: Flash Cache internal write MiB/s",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "FC_IO_BY_W_POPULATE_SEC{server=~\"$server\"}",
     "legendFormat": "Population-{{server}}"
    },
    {
     "expr": "FC_IO_BY_W_METADATA_SEC{server=~\"$server\"}",
     "legendFormat": "Metadata-{{server}}"
    }
   ]
  }
 ]
}