{
 "title": "IORM Database",
 "tags": [
  "exadata",
  "storage",
  "prometheus",
  "iormdb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   },
   {
    "name": "dbname",
    "query": {
     "query": "label_values({__name__=~\"DB_FD_IO_RQ_SM_SEC|DB_IO_RQ_SM_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",server=~\"$server\"},objectName)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flash Cache Allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "DB_FC_BY_ALLOCATED{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IOs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flash IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server,objectName) ({__name__=~\"DB_FD_IO_RQ_SM_SEC|DB_FD_IO_RQ_LG_SEC\",server=~\"$server\",objectName=~\"${dbname}\"})",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server, objectName) ({__name__=~\"DB_IO_RQ_SM_SEC|DB_CF_IO_RQ_SM_SEC|DB_IO_RQ_LG_SEC|DB_CF_IO_RQ_LG_SEC\",server=~\"$server\",objectName=~\"$dbname\"})",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Small IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "DB_FD_IO_RQ_SM_SEC{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Large IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "DB_FD_IO_RQ_LG_SEC{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Small IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "{__name__=~\"DB_IO_RQ_SM_SEC|DB_CF_IO_RQ_SM_SEC\",server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Large IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "{__name__=~\"DB_IO_RQ_LG_SEC|DB_CF_IO_RQ_LG_SEC\",server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency and Queue Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flash Small IO Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "DB_FD_IO_TM_SM_RQ{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Large IO Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "DB_FD_IO_TM_LG_RQ{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "{__name__=~\"DB_IO_TM_SM_RQ|DB_CF_IO_TM_SM_RQ\",server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Large IO Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"DB_IO_TM_LG_RQ|DB_CF_IO_TM_LG_RQ\",server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Small IO IORM Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "DB_FD_IO_WT_SM_RQ{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Small IO IORM Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "DB_FD_IO_WT_LG_RQ{server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Small IO IORM Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "{__name__=~\"DB_IO_WT_SM_RQ|DB_CF_IO_WT_SM_RQ\",server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Large IO IORM Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "{__name__=~\"DB_IO_WT_LG_RQ|DB_CF_IO_WT_LG_RQ\",server=~\"$server\",objectName=~\"$dbname\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}