{
 "title": "Network",
 "description": "Network Information",
 "tags": [
  "exadata",
  "prometheus",
  "compute",
  "storage",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "fleet",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\"}"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\",fleet=\"$fleet\"}"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\",fleet=\"$fleet\",pod=\"$pod\"}"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "{__name__=~\"CL_CPUT|DS_CPUT\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "{__name__=~\"EXW_ROCE_RX_BY_SEC|EXW_ROCE_TX_BY_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",server=~\"$server\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RX Bytes - ($interface)",
   "type": "timeseries",
   "description": "EXAREL: RoCE bytes received",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_ROCE_RX_BY_SEC{server=~\"$server\", objectName=~\"${interface}.*\"}",
     "legendFormat": "{{objectName}}-{{server}}"
    },
    {
     "expr": "N_IB_MB_RCV_SEC{server=~\"$server\"}",
     "legendFormat": "{{objectName}}-{{server}}"
    }
   ]
  },
  {
   "title": "TX Bytes - ($interface)",
   "type": "timeseries",
   "description": "EXAREL: RoCE bytes transmitted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_ROCE_TX_BY_SEC{server=~\"$server\",objectName=~\"${interface}.*\"}",
     "legendFormat": "{{objectName}}-{{server}}"
    },
    {
     "expr": "N_IB_MB_TRANS_SEC{server=~\"$server\"}",
     "legendFormat": "{{objectName}}-{{server}}"
    }
   ]
  },
  {
   "title": "Pauses ($interface)",
   "type": "timeseries",
   "description": "EXAREL: RoCE Pause Frames or IB Pauses",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "repeat": "interface",
   "targets": [
    {
     "constant": 6.5,
     "expr": "delta(EXW_ROCE_PAUSE{server=~\"$server\",objectName=~\"${interface}.*\"}[1m])",
     "legendFormat": "{{objectName}}-{{server}}"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RDS Ping (Lane 0)",
   "type": "timeseries",
   "description": "EXAREL: RDS Ping on Lane Zero",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_RDS_PING_0{server=~\"$server\"}",
     "legendFormat": "{{objectName}}"
    }
   ]
  },
  {
   "title": "RDS Errors",
   "type": "timeseries",
   "description": "EXAREL: rds-info counters",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "constant": 6.5,
     "expr": "delta(EXW_RDS_CONG_SEND_BLOCKED{server=~\"$server\"}[5m])",
     "legendFormat": "RDS_CONG_SEND_BLKD-{{server}}"
    },
    {
     "expr": "delta(EXW_RDS_CONG_SEND_ERROR{server=~\"$server\"}[5m])",
     "legendFormat": "RDS_CONG_SEND_ERROR-{{server}}"
    },
    {
     "expr": "delta(EXW_RDS_IB_MR_1M_POOL_DEPLETED{server=~\"$server\"}[5m])",
     "legendFormat": "RDS_IB_MR_1M_POOL_DEPLETED-{{server}}"
    },
    {
     "expr": "delta(EXW_RDS_IB_RDMA_MR_8K_POOL_DEPLETED{server=~\"$server\"}[5m])",
     "legendFormat": "RDS_IB_RDMA_MR_8K_POOL_DEPLETED({{server}})"
    },
    {
     "expr": "delta(EXW_RDS_IB_TX_STALLED{server=~\"$server\"}[5m])",
     "legendFormat": "RDS_IB_TX_STALLED-{{server}}"
    },
    {
     "expr": "delta(EXW_ROCE_RNR_NAK_RETRY_ERR{server=~\"$server\"}[5m])",
     "legendFormat": "RNR_NAK_RETRY_ERR-{{server}}-{{objectName}}"
    },
    {
     "expr": "delta(EXW_ROCE_LOCAL_ACK_TIMEOUT_ERR{server=~\"$server\"}[5m])",
     "legendFormat": "LOCAL_ACK_TIMEOUT_ERR-{{server}}-{{objectName}}"
    }
   ]
  }
 ]
}