{
 "title": "Smart Scan",
 "tags": [
  "exadata",
  "storage",
  "smartscan",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "CL_CPUT" } },
   {
    "name": "pod",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\"}"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"}"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "EXAREL: cpu utilization on the cells",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "CL_CPUT{server=~\"$server\"}",
     "legendFormat": "%cell cpu-{{server}}"
    },
    {
     "expr": "CL_CPUT_CS{server=~\"$server\"}",
     "legendFormat": "%cellsrv cpu-{{server}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "description": "EXAREL: %memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_CELLMEM_OS_AVAIL_PCT{server=~\"$server\"}",
     "legendFormat": "%OS available-{{server}}"
    },
    {
     "expr": "EXW_CELLMEM_CELL_AVAIL_PCT{server=~\"$server\"}",
     "legendFormat": "%cellsrv available-{{server}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "EXAREL: Memory Usagse",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_CELLMEM_OS_TOTAL{server=~\"$server\"}",
     "legendFormat": "Total-{{server}}"
    },
    {
     "expr": "EXW_CELLMEM_OS_KNL{server=~\"$server\"}",
     "legendFormat": "OS kernel-{{server}}"
    },
    {
     "expr": "EXW_CELLMEM_OS_USR{server=~\"$server\"}",
     "legendFormat": "OS user-{{server}}"
    }
   ]
  },
  {
   "title": "Cellsrv Memory",
   "type": "timeseries",
   "description": "EXAREL: cellsrv memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "EXW_CELLMEM_CELL_CELLSRV{server=\"$server\"}",
     "legendFormat": "cellsrv-{{server}}"
    },
    {
     "expr": "EXW_CELLMEM_CELL_OFFLOAD{server=~\"$server\"}",
     "legendFormat": "offload-{{server}}"
    },
    {
     "expr": "EXW_CELLMEM_CELL_KNL{server=~\"$server\"}",
     "legendFormat": "kernel-{{server}}"
    }
   ]
  },
  {
   "title": "Smart Scans",
   "type": "timeseries",
   "description": "EXAREL: smart IO",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "SIO_IO_EL_OF_SEC{server=~\"$server\"}",
     "legendFormat": "Eligible-{{server}}"
    },
    {
     "expr": "SIO_IO_OF_RE_SEC{server=~\"$server\"}",
     "legendFormat": "Returned-{{server}}"
    },
    {
     "expr": "SIO_IO_PA_TH_SEC{server=\"$server\"}",
     "legendFormat": "Passthru-{{server}}"
    },
    {
     "expr": "SIO_IO_RV_OF_SEC{server=~\"$server\"}",
     "legendFormat": "Reverse Offload-{{server}}"
    }
   ]
  },
  {
   "title": "Smart Scan IO Target",
   "type": "timeseries",
   "description": "EXAREL: media servicing the smart scans",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "SIO_IO_RD_FC_SEC{server=~\"$server\"}",
     "legendFormat": "Flash-{{server}}"
    },
    {
     "expr": "SIO_IO_RD_HD_SEC{server=~\"$server\"}",
     "legendFormat": "Disk-{{server}}"
    },
    {
     "expr": "SIO_IO_RD_FC_HD_SEC{server=~\"$server\"}",
     "legendFormat": "Both-{{server}}"
    }
   ]
  },
  {
   "title": "Columnar Cache",
   "type": "timeseries",
   "description": "EXAREL: Columnar Cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "FC_COL_IO_BY_R_ELIGIBLE_SEC{server=~\"$server\"}",
     "legendFormat": "CC Eligible-{{server}}"
    },
    {
     "expr": "FC_COL_IO_BY_R_SEC{server=~\"$server\"}",
     "legendFormat": "CC Read-{{server}}"
    },
    {
     "expr": "FC_COL_IO_BY_SAVED_SEC{server=~\"$server\"}",
     "legendFormat": "CC Saved-{{server}}"
    }
   ]
  },
  {
   "title": "Storage Index",
   "type": "timeseries",
   "description": "EXAREL: Smart Scan SI savings",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "SIO_IO_SI_SV_SEC{server=~\"$server\"}",
     "legendFormat": "SI savings-{{server}}"
    }
   ]
  }
 ]
}