{
 "title": "Storage Server",
 "tags": [
  "storage",
  "server",
  "exadata",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   },
   {
    "name": "deviceType",
    "query": {
     "query": "{__name__=~\"CD_IO_RQ_R_SM_SEC|CD_IO_RQ_W_SM_SEC|CD_IO_RQ_R_LG_SEC|CD_IO_RQ_W_LG_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName!~\"PM_.*\"}"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "EXAREL: CPU utilization",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "CL_CPUT{server=~\"$server\"}",
       "legendFormat": "%CPU-{{server}}"
      }
     ]
    },
    {
     "title": "RX Bytes - RDMA",
     "type": "timeseries",
     "description": "EXAREL: Network RX bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "sum by (server) (EXW_ROCE_RX_BY_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-RoCE"
      },
      {
       "expr": "sum by (server) (N_IB_MB_RCV_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-IB"
      }
     ]
    },
    {
     "title": "TX Bytes - RDMA",
     "type": "timeseries",
     "description": "EXAREL: Network TX bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (EXW_ROCE_TX_BY_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-RoCE"
      },
      {
       "expr": "sum by (server) (N_IB_MB_TRANS_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-IB"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "timeseries",
     "description": "EXAREL: Percentage of memory available",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_CELLMEM_OS_AVAIL_PCT{server=~\"$server\"}",
       "legendFormat": "%OS available-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_CELL_AVAIL_PCT{server=~\"$server\"}",
       "legendFormat": "%cellsrv available-{{server}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "EXAREL: Memory Usage",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_CELLMEM_OS_TOTAL{server=~\"$server\"}",
       "legendFormat": "Total-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_OS_KNL{server=~\"$server\"}",
       "legendFormat": "OS kernel-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_OS_USR{server=~\"$server\"}",
       "legendFormat": "OS usr-{{server}}"
      }
     ]
    },
    {
     "title": "Cellsrv Memory",
     "type": "timeseries",
     "description": "EXAREL: Cellsrv memory usage",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_CELLMEM_CELL_KNL{server=~\"$server\"}",
       "legendFormat": "kernel-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_CELL_CELLSRV{server=~\"$server\"}",
       "legendFormat": "cellsrv-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_CELL_OFFLOAD{server=~\"$server\"}",
       "legendFormat": "offload-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_OTHER_SERV{server=~\"$server\"}",
       "legendFormat": "other services-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cell Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IOPs - $deviceType",
     "type": "timeseries",
     "description": "EXAREL: IO requests on $deviceType\nFD: Flash\nCD: Hard Disk",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "repeat": "deviceType",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (server) (CD_IO_RQ_R_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Small Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_W_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Small Writes-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_R_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Large Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_W_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Large Writes-{{server}}"
      }
     ]
    },
    {
     "title": "MiB/s - $deviceType",
     "type": "timeseries",
     "description": "EXAREL: IO MiB/s on $deviceType\nFD: Flash\nCD: Hard Disk",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "repeat": "deviceType",
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "sum by (server) (CD_IO_BY_R_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Small Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_W_SM_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Small Writes-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_R_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Large Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_W_LG_SEC{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Large Writes-{{server}}"
      }
     ]
    },
    {
     "title": "Latency - $deviceType",
     "type": "timeseries",
     "description": "EXAREL: Average latency on $deviceType\nFD: Flash \nCD: Hard Disk",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "repeat": "deviceType",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (server) (CD_IO_TM_R_SM_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Small Reads-{{server}}"
      },
      {
       "expr": "avg by (server) (CD_IO_TM_W_SM_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Small Writes-{{server}}"
      },
      {
       "expr": "avg by (server) (CD_IO_TM_R_LG_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Large Reads-{{server}}"
      },
      {
       "expr": "avg by (server) (CD_IO_TM_W_LG_RQ{objectName=~\"${deviceType}_.*\",server=~\"$server\"})",
       "legendFormat": "Large Writes-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IORM Queue Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flash IORM Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "DB_FD_IO_WT_SM_RQ{server=~\"$server\"}",
       "legendFormat": "Small IO-{{objectName}}-{{server}}"
      },
      {
       "expr": "DB_FD_IO_WT_LG_RQ{server=~\"$server\"}",
       "legendFormat": "Large IO-{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Disk IORM Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "{__name__=~\"DB_IO_WT_SM_RQ|DB_CF_IO_WT_SM_RQ\",server=~\"$server\"}",
       "legendFormat": "Small IO-{{objectName}}-{{server}}"
      },
      {
       "expr": "{__name__=~\"DB_IO_WT_LG_RQ|DB_CF_IO_WT_LG_RQ\",server=~\"$server\"}",
       "legendFormat": "Large IO-{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flash Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flash Cache User Reads Requests",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache User Read Requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "FC_IO_RQ_R_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP reads-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan reads-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP misses-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_MISS_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan misses-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache User Reads MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache User Read MiB/s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FC_IO_BY_R_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP reads-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan reads-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP misses-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_MISS_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan misses-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Smart Scan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Smart Scan IO",
     "type": "timeseries",
     "description": "EXAREL: Smart Scan IO Activity",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "SIO_IO_EL_OF_SEC{server=~\"$server\"}",
       "legendFormat": "Eligible-{{server}}"
      },
      {
       "expr": "SIO_IO_OF_RE_SEC{server=~\"$server\"}",
       "legendFormat": "Returned-{{server}}"
      }
     ]
    },
    {
     "title": "Columnar Cache",
     "type": "timeseries",
     "description": "EXAREL: Columnar Cache IO Activity",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FC_COL_IO_BY_R_ELIGIBLE_SEC{server=~\"$server\"}",
       "legendFormat": "Eligible-{{server}}"
      },
      {
       "expr": "FC_COL_IO_BY_R_SEC{server=~\"$server\"}",
       "legendFormat": "Read-{{server}}"
      },
      {
       "expr": "FC_COL_IO_BY_SAVED_SEC{server=~\"$server\"}",
       "legendFormat": "Saved-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flash Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flash Log Requests",
     "type": "timeseries",
     "description": "EXAREL: Flash Log write requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate (FL_IO_W{server=~\"$server\"}[1m])",
       "legendFormat": "Writes-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Log MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Flash Log write MiB/s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FL_IO_FL_BY_W_SEC{server=~\"$server\"}",
       "legendFormat": "Flash Log-{{server}}"
      },
      {
       "expr": "FL_IO_DB_BY_W_SEC{server=~\"$server\"}",
       "legendFormat": "DB Log-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}