drop table html_files;
create table html_files (filename varchar2(255), filedata varchar2(255));

insert into html_files values ('/eddie/h/auser/home/html/abconf.htm', '/eddie/h/auser/home/html/abconf.htm');
insert into html_files values ('/eddie/h/auser/home/html/addbike.htm', '/eddie/h/auser/home/html/addbike.htm');
insert into html_files values ('/eddie/h/auser/home/html/alanruss.htm', '/eddie/h/auser/home/html/alanruss.htm');
insert into html_files values ('/eddie/h/auser/home/html/armour.htm', '/eddie/h/auser/home/html/armour.htm');
insert into html_files values ('/eddie/h/auser/home/html/ayprof.htm', '/eddie/h/auser/home/html/ayprof.htm');
insert into html_files values ('/eddie/h/auser/home/html/back.htm', '/eddie/h/auser/home/html/back.htm');
insert into html_files values ('/eddie/h/auser/home/html/bemhist.htm', '/eddie/h/auser/home/html/bemhist.htm');
insert into html_files values ('/eddie/h/auser/home/html/bemsee.htm', '/eddie/h/auser/home/html/bemsee.htm');
insert into html_files values ('/eddie/h/auser/home/html/ben-champ.htm', '/eddie/h/auser/home/html/ben-champ.htm');
insert into html_files values ('/eddie/h/auser/home/html/bh090802.htm', '/eddie/h/auser/home/html/bh090802.htm');
insert into html_files values ('/eddie/h/auser/home/html/bikes.htm', '/eddie/h/auser/home/html/bikes.htm');
insert into html_files values ('/eddie/h/auser/home/html/br020900.htm', '/eddie/h/auser/home/html/br020900.htm');
insert into html_files values ('/eddie/h/auser/home/html/br090302.htm', '/eddie/h/auser/home/html/br090302.htm');
insert into html_files values ('/eddie/h/auser/home/html/br090602.htm', '/eddie/h/auser/home/html/br090602.htm');
insert into html_files values ('/eddie/h/auser/home/html/br091000.htm', '/eddie/h/auser/home/html/br091000.htm');
insert into html_files values ('/eddie/h/auser/home/html/br120300.htm', '/eddie/h/auser/home/html/br120300.htm');
insert into html_files values ('/eddie/h/auser/home/html/br120501.htm', '/eddie/h/auser/home/html/br120501.htm');
insert into html_files values ('/eddie/h/auser/home/html/br12797.htm', '/eddie/h/auser/home/html/br12797.htm');
insert into html_files values ('/eddie/h/auser/home/html/br1397.htm', '/eddie/h/auser/home/html/br1397.htm');
insert into html_files values ('/eddie/h/auser/home/html/br220400.htm', '/eddie/h/auser/home/html/br220400.htm');
insert into html_files values ('/eddie/h/auser/home/html/br23397.htm', '/eddie/h/auser/home/html/br23397.htm');
insert into html_files values ('/eddie/h/auser/home/html/br271001.htm', '/eddie/h/auser/home/html/br271001.htm');
insert into html_files values ('/eddie/h/auser/home/html/br280500.htm', '/eddie/h/auser/home/html/br280500.htm');
insert into html_files values ('/eddie/h/auser/home/html/br51097.htm', '/eddie/h/auser/home/html/br51097.htm');
insert into html_files values ('/eddie/h/auser/home/html/br980301.htm', '/eddie/h/auser/home/html/br980301.htm');
insert into html_files values ('/eddie/h/auser/home/html/br98712.htm', '/eddie/h/auser/home/html/br98712.htm');
insert into html_files values ('/eddie/h/auser/home/html/brandoct.htm', '/eddie/h/auser/home/html/brandoct.htm');
insert into html_files values ('/eddie/h/auser/home/html/brands.htm', '/eddie/h/auser/home/html/brands.htm');
insert into html_files values ('/eddie/h/auser/home/html/ca060500.htm', '/eddie/h/auser/home/html/ca060500.htm');
insert into html_files values ('/eddie/h/auser/home/html/ca080899.htm', '/eddie/h/auser/home/html/ca080899.htm');
insert into html_files values ('/eddie/h/auser/home/html/ca120800.htm', '/eddie/h/auser/home/html/ca120800.htm');
insert into html_files values ('/eddie/h/auser/home/html/ca180801.htm', '/eddie/h/auser/home/html/ca180801.htm');
insert into html_files values ('/eddie/h/auser/home/html/ca5797.htm', '/eddie/h/auser/home/html/ca5797.htm');
insert into html_files values ('/eddie/h/auser/home/html/cadbrief.htm', '/eddie/h/auser/home/html/cadbrief.htm');
insert into html_files values ('/eddie/h/auser/home/html/cadwell.htm', '/eddie/h/auser/home/html/cadwell.htm');
insert into html_files values ('/eddie/h/auser/home/html/ champ.htm', '/eddie/h/auser/home/html/champ.htm');
insert into html_files values ('/eddie/h/auser/home/html/change2001.htm', '/eddie/h/auser/home/html/change2001.htm');
insert into html_files values ('/eddie/h/auser/home/html/clubnews.htm', '/eddie/h/auser/home/html/clubnews.htm');
insert into html_files values ('/eddie/h/auser/home/html/counter.htm', '/eddie/h/auser/home/html/counter.htm');
insert into html_files values ('/eddie/h/auser/home/html/cr24597.htm', '/eddie/h/auser/home/html/cr24597.htm');
insert into html_files values ('/eddie/h/auser/home/html/cr980721.htm', '/eddie/h/auser/home/html/cr980721.htm');
insert into html_files values ('/eddie/h/auser/home/html/dbprof.htm', '/eddie/h/auser/home/html/dbprof.htm');
insert into html_files values ('/eddie/h/auser/home/html/dfprof.htm', '/eddie/h/auser/home/html/dfprof.htm');
insert into html_files values ('/eddie/h/auser/home/html/do110301.htm', '/eddie/h/auser/home/html/do110301.htm');
insert into html_files values ('/eddie/h/auser/home/html/dt.htm', '/eddie/h/auser/home/html/dt.htm');
insert into html_files values ('/eddie/h/auser/home/html/dynotech.htm', '/eddie/h/auser/home/html/dynotech.htm');
insert into html_files values ('/eddie/h/auser/home/html/emacs.htm', '/eddie/h/auser/home/html/emacs.htm');
insert into html_files values ('/eddie/h/auser/home/html/fit.htm', '/eddie/h/auser/home/html/fit.htm');
insert into html_files values ('/eddie/h/auser/home/html/footer.htm', '/eddie/h/auser/home/html/footer.htm');
insert into html_files values ('/eddie/h/auser/home/html/gfile.htm', '/eddie/h/auser/home/html/gfile.htm');
insert into html_files values ('/eddie/h/auser/home/html/gfstory.htm', '/eddie/h/auser/home/html/gfstory.htm');
insert into html_files values ('/eddie/h/auser/home/html/gj1997.htm', '/eddie/h/auser/home/html/gj1997.htm');
insert into html_files values ('/eddie/h/auser/home/html/gjgallery.htm', '/eddie/h/auser/home/html/gjgallery.htm');
insert into html_files values ('/eddie/h/auser/home/html/gjones.htm', '/eddie/h/auser/home/html/gjones.htm');
insert into html_files values ('/eddie/h/auser/home/html/glyn97.htm', '/eddie/h/auser/home/html/glyn97.htm');
insert into html_files values ('/eddie/h/auser/home/html/glyn97.htm', '/eddie/h/auser/home/html/glyn97.htm');
insert into html_files values ('/eddie/h/auser/home/html/index1.htm', '/eddie/h/auser/home/html/index1.htm');
insert into html_files values ('/eddie/h/auser/home/html/index.htm', '/eddie/h/auser/home/html/index.htm');
insert into html_files values ('/eddie/h/auser/home/html/index (raford v1).htm', '/eddie/h/auser/home/html/index (raford v1).htm');
insert into html_files values ('/eddie/h/auser/home/html/join.htm', '/eddie/h/auser/home/html/join.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly050300.htm', '/eddie/h/auser/home/html/ly050300.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly050301.htm', '/eddie/h/auser/home/html/ly050301.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly060901.htm', '/eddie/h/auser/home/html/ly060901.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly061001.htm', '/eddie/h/auser/home/html/ly061001.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly061001 (raford v1).htm', '/eddie/h/auser/home/html/ly061001 (raford v1).htm');
insert into html_files values ('/eddie/h/auser/home/html/ly12497.htm', '/eddie/h/auser/home/html/ly12497.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly150700.htm', '/eddie/h/auser/home/html/ly150700.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly160900.htm', '/eddie/h/auser/home/html/ly160900.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly180499.htm', '/eddie/h/auser/home/html/ly180499.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly181097.htm', '/eddie/h/auser/home/html/ly181097.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly200399.htm', '/eddie/h/auser/home/html/ly200399.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly21697.htm', '/eddie/h/auser/home/html/ly21697.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly250502.htm', '/eddie/h/auser/home/html/ly250502.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly2597.htm', '/eddie/h/auser/home/html/ly2597.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly260699.htm', '/eddie/h/auser/home/html/ly260699.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly29397.htm', '/eddie/h/auser/home/html/ly29397.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly3597.htm', '/eddie/h/auser/home/html/ly3597.htm');
insert into html_files values ('/eddie/h/auser/home/html/ly980328.htm', '/eddie/h/auser/home/html/ly980328.htm');
insert into html_files values ('/eddie/h/auser/home/html/lyd31896.htm', '/eddie/h/auser/home/html/lyd31896.htm');
insert into html_files values ('/eddie/h/auser/home/html/lyd89.htm', '/eddie/h/auser/home/html/lyd89.htm');
insert into html_files values ('/eddie/h/auser/home/html/lydoct.htm', '/eddie/h/auser/home/html/lydoct.htm');
insert into html_files values ('/eddie/h/auser/home/html/ma230700.htm', '/eddie/h/auser/home/html/ma230700.htm');
insert into html_files values ('/eddie/h/auser/home/html/ma270700.htm', '/eddie/h/auser/home/html/ma270700.htm');
insert into html_files values ('/eddie/h/auser/home/html/memform.htm', '/eddie/h/auser/home/html/memform.htm');
insert into html_files values ('/eddie/h/auser/home/html/mille.htm', '/eddie/h/auser/home/html/mille.htm');
insert into html_files values ('/eddie/h/auser/home/html/minimoto.htm', '/eddie/h/auser/home/html/minimoto.htm');
insert into html_files values ('/eddie/h/auser/home/html/mro-dates2001.htm', '/eddie/h/auser/home/html/mro-dates2001.htm');
insert into html_files values ('/eddie/h/auser/home/html/new.htm', '/eddie/h/auser/home/html/new.htm');
insert into html_files values ('/eddie/h/auser/home/html/newindex.htm', '/eddie/h/auser/home/html/newindex.htm');
insert into html_files values ('/eddie/h/auser/home/html/notfound.htm', '/eddie/h/auser/home/html/notfound.htm');
insert into html_files values ('/eddie/h/auser/home/html/nrdiary.htm', '/eddie/h/auser/home/html/nrdiary.htm');
insert into html_files values ('/eddie/h/auser/home/html/oldindex.htm', '/eddie/h/auser/home/html/oldindex.htm');
insert into html_files values ('/eddie/h/auser/home/html/ou010402.htm', '/eddie/h/auser/home/html/ou010402.htm');
insert into html_files values ('/eddie/h/auser/home/html/ou080700.htm', '/eddie/h/auser/home/html/ou080700.htm');
insert into html_files values ('/eddie/h/auser/home/html/ou100600.htm', '/eddie/h/auser/home/html/ou100600.htm');
insert into html_files values ('/eddie/h/auser/home/html/ou140599.htm', '/eddie/h/auser/home/html/ou140599.htm');
insert into html_files values ('/eddie/h/auser/home/html/ou160401.htm', '/eddie/h/auser/home/html/ou160401.htm');
insert into html_files values ('/eddie/h/auser/home/html/ou300601.htm', '/eddie/h/auser/home/html/ou300601.htm');
insert into html_files values ('/eddie/h/auser/home/html/painting.htm', '/eddie/h/auser/home/html/painting.htm');
insert into html_files values ('/eddie/h/auser/home/html/ppbrands.htm', '/eddie/h/auser/home/html/ppbrands.htm');
insert into html_files values ('/eddie/h/auser/home/html/ppdonn.htm', '/eddie/h/auser/home/html/ppdonn.htm');
insert into html_files values ('/eddie/h/auser/home/html/ppprof.htm', '/eddie/h/auser/home/html/ppprof.htm');
insert into html_files values ('/eddie/h/auser/home/html/pprof.htm', '/eddie/h/auser/home/html/pprof.htm');
insert into html_files values ('/eddie/h/auser/home/html/ppsnett.htm', '/eddie/h/auser/home/html/ppsnett.htm');
insert into html_files values ('/eddie/h/auser/home/html/pr11996.htm', '/eddie/h/auser/home/html/pr11996.htm');
insert into html_files values ('/eddie/h/auser/home/html/pre2001.htm', '/eddie/h/auser/home/html/pre2001.htm');
insert into html_files values ('/eddie/h/auser/home/html/prep98.htm', '/eddie/h/auser/home/html/prep98.htm');
insert into html_files values ('/eddie/h/auser/home/html/quiz.htm', '/eddie/h/auser/home/html/quiz.htm');
insert into html_files values ('/eddie/h/auser/home/html/racebike.htm', '/eddie/h/auser/home/html/racebike.htm');
insert into html_files values ('/eddie/h/auser/home/html/racefaq.htm', '/eddie/h/auser/home/html/racefaq.htm');
insert into html_files values ('/eddie/h/auser/home/html/rb1997.htm', '/eddie/h/auser/home/html/rb1997.htm');
insert into html_files values ('/eddie/h/auser/home/html/rdates.htm', '/eddie/h/auser/home/html/rdates.htm');
insert into html_files values ('/eddie/h/auser/home/html/replist.htm', '/eddie/h/auser/home/html/replist.htm');
insert into html_files values ('/eddie/h/auser/home/html/rf1996.htm', '/eddie/h/auser/home/html/rf1996.htm');
insert into html_files values ('/eddie/h/auser/home/html/rfcroix.htm', '/eddie/h/auser/home/html/rfcroix.htm');
insert into html_files values ('/eddie/h/auser/home/html/rfprof.htm', '/eddie/h/auser/home/html/rfprof.htm');
insert into html_files values ('/eddie/h/auser/home/html/rftt.htm', '/eddie/h/auser/home/html/rftt.htm');
insert into html_files values ('/eddie/h/auser/home/html/rgvsale.htm', '/eddie/h/auser/home/html/rgvsale.htm');
insert into html_files values ('/eddie/h/auser/home/html/search1.htm', '/eddie/h/auser/home/html/search1.htm');
insert into html_files values ('/eddie/h/auser/home/html/search2.htm', '/eddie/h/auser/home/html/search2.htm');
insert into html_files values ('/eddie/h/auser/home/html/search.htm', '/eddie/h/auser/home/html/search.htm');
insert into html_files values ('/eddie/h/auser/home/html/si070401.htm', '/eddie/h/auser/home/html/si070401.htm');
insert into html_files values ('/eddie/h/auser/home/html/si211000.htm', '/eddie/h/auser/home/html/si211000.htm');
insert into html_files values ('/eddie/h/auser/home/html/si241099.htm', '/eddie/h/auser/home/html/si241099.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn010400.htm', '/eddie/h/auser/home/html/sn010400.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn040502.htm', '/eddie/h/auser/home/html/sn040502.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn07697.htm', '/eddie/h/auser/home/html/sn07697.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn080901.htm', '/eddie/h/auser/home/html/sn080901.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn170600.htm', '/eddie/h/auser/home/html/sn170600.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn190800.htm', '/eddie/h/auser/home/html/sn190800.htm');
insert into html_files values ('/eddie/h/auser/home/html/sn6hr96.htm', '/eddie/h/auser/home/html/sn6hr96.htm');
insert into html_files values ('/eddie/h/auser/home/html/snett1.htm', '/eddie/h/auser/home/html/snett1.htm');
insert into html_files values ('/eddie/h/auser/home/html/sponsor.htm', '/eddie/h/auser/home/html/sponsor.htm');
insert into html_files values ('/eddie/h/auser/home/html/strtrace.htm', '/eddie/h/auser/home/html/strtrace.htm');
insert into html_files values ('/eddie/h/auser/home/html/tdbrief.htm', '/eddie/h/auser/home/html/tdbrief.htm');
insert into html_files values ('/eddie/h/auser/home/html/team.htm', '/eddie/h/auser/home/html/team.htm');
insert into html_files values ('/eddie/h/auser/home/html/tech.htm', '/eddie/h/auser/home/html/tech.htm');
insert into html_files values ('/eddie/h/auser/home/html/th030601.htm', '/eddie/h/auser/home/html/th030601.htm');
insert into html_files values ('/eddie/h/auser/home/html/thrash3.htm', '/eddie/h/auser/home/html/thrash3.htm');
insert into html_files values ('/eddie/h/auser/home/html/Tigger.htm', '/eddie/h/auser/home/html/Tigger.htm');
insert into html_files values ('/eddie/h/auser/home/html/trackday.htm', '/eddie/h/auser/home/html/trackday.htm');
insert into html_files values ('/eddie/h/auser/home/html/tshirts.htm', '/eddie/h/auser/home/html/tshirts.htm');
insert into html_files values ('/eddie/h/auser/home/html/tzdyno.htm', '/eddie/h/auser/home/html/tzdyno.htm');
insert into html_files values ('/eddie/h/auser/home/html/tz.htm', '/eddie/h/auser/home/html/tz.htm');
insert into html_files values ('/eddie/h/auser/home/html/update98.htm', '/eddie/h/auser/home/html/update98.htm');
insert into html_files values ('/eddie/h/auser/home/html/wizcomp.htm', '/eddie/h/auser/home/html/wizcomp.htm');
insert into html_files values ('/eddie/h/auser/home/html/wiz.htm', '/eddie/h/auser/home/html/wiz.htm');
insert into html_files values ('/eddie/h/auser/home/html/x.htm', '/eddie/h/auser/home/html/x.htm');

alter table html_files add (pk number primary key);
update html_files set pk = rownum;
commit;

exec ctx_ddl.drop_section_group ('msg')
exec ctx_ddl.create_section_group ('msg', 'html_section_group')

set timing on

create index html_files_index on html_files (filedata)
indextype is ctxsys.context 
parameters ('datastore ctxsys.file_datastore filter ctxsys.null_filter section group msg');


