-- Example Tables
CREATE TABLE TEAMS (
                       ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       TEAM_NAME VARCHAR2(80),
                       TEAM_REGION VARCHAR2(80),
                       TEAM_COLOR VARCHAR2(6)
);

CREATE TABLE PLAYERS (
                         ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         USERNAME VARCHAR2(80),
                         TEAM_ID NUMBER references TEAMS (ID) on delete set null,
                         PLAYER_POSITION VARCHAR2(50)
);

CREATE TABLE AWARDS (
                        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        AWARD_NAME VARCHAR2(250),
                        AWARDED_ON DATE default SYSDATE,
                        PLAYER_ID NUMBER references PLAYERS (ID) on delete cascade,
                        AWARD_DETAILS JSON -- Native JSON Datatype
);

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW team_info_dv AS
SELECT JSON {
        '_id'         : t.ID,
    'name'           : t.TEAM_NAME,
    'region'         : t.TEAM_REGION,
    'color'          : t.TEAM_COLOR,
    'players': [
SELECT JSON {
        'playerId'   : p.ID,
    'name'       : p.USERNAME,
    'position'   : p.PLAYER_POSITION
    } from PLAYERS p WITH INSERT UPDATE DELETE
          where p.TEAM_ID = t.ID
]}
FROM TEAMS t WITH INSERT UPDATE DELETE


CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW player_team_info_dv AS
SELECT JSON {
    '_id'      : p.ID,
    'name'          : p.USERNAME,
    'position'      : p.PLAYER_POSITION,
    UNNEST (
SELECT JSON {
    'teamId'        : t.ID,
    'teamName'      : t.TEAM_NAME,
    'teamRegion'    : t.TEAM_REGION
    } from TEAMS t with NOUPDATE NOINSERT NODELETE
      where p.TEAM_ID = t.ID
)}
FROM PLAYERS p WITH INSERT UPDATE DELETE



 -- INSERT data
INSERT INTO TEAMS (TEAM_NAME, TEAM_REGION, TEAM_COLOR) VALUES ('Crimson Warriors', 'North America', 'FF0000');
INSERT INTO TEAMS (TEAM_NAME, TEAM_REGION, TEAM_COLOR) VALUES ('Shadow Raiders', 'North America', '000000');

INSERT INTO PLAYERS (ID, USERNAME, TEAM_ID, PLAYER_POSITION) VALUES (1, 'PLAYER_ANDY', 1, 'Offense');
INSERT INTO PLAYERS (ID, USERNAME, TEAM_ID, PLAYER_POSITION) VALUES (2, 'PLAYER_BARRY', 1, 'Defense');
INSERT INTO PLAYERS (ID, USERNAME, TEAM_ID, PLAYER_POSITION) VALUES (3, 'PLAYER_CARL', 1, 'Support');
INSERT INTO PLAYERS (ID, USERNAME, TEAM_ID, PLAYER_POSITION) VALUES (4, 'PLAYER_DESMOND', 2, 'Offense');
INSERT INTO PLAYERS (ID, USERNAME, TEAM_ID, PLAYER_POSITION) VALUES (5, 'PLAYER_ERIC', 2, 'Defense');
INSERT INTO PLAYERS (ID, USERNAME, TEAM_ID, PLAYER_POSITION) VALUES (6, 'PLAYER_FARIS', 2, 'Tank');

INSERT INTO AWARDS (PLAYER_ID, AWARD_NAME, AWARD_DETAILS) VALUES (1, 'Highest Damage', '{"pts": 20, "damage": 120300}');
INSERT INTO AWARDS (PLAYER_ID, AWARD_NAME, AWARD_DETAILS) VALUES (4, 'Best Defense', '{"pts": 20, "receivedDamage": 322199}');