# The following creates and populates the tables used for the tutorial
# These scripts use identity columns available in Oracle 12.1.  If you are using an older version you will need
#   to add your own trigger/sequence functionality to generate the id values.
# code Sample from the tutorial at https://learncodeshare.net/2016/08/26/basic-crud-operations-using-ruby-oci8/

CREATE TABLE LCS_PEOPLE (
 id NUMBER GENERATED BY DEFAULT AS identity,
 name VARCHAR2(20),
 age NUMBER,
 notes VARCHAR2(100)
)
/

ALTER TABLE LCS_PEOPLE
ADD CONSTRAINT PK_LCS_PEOPLE PRIMARY KEY ("ID")
/

CREATE TABLE LCS_PETS (
 id NUMBER GENERATED BY DEFAULT AS IDENTITY,
 name VARCHAR2(20),
 owner NUMBER,
 type VARCHAR2(100)
)
/

ALTER TABLE LCS_PETS ADD CONSTRAINT PK_LCS_PETS PRIMARY KEY ("ID")
/

ALTER TABLE LCS_PETS ADD CONSTRAINT FK_LCS_PETS_OWNER FOREIGN KEY ("OWNER") REFERENCES "LCS_PEOPLE" ("ID")
/

INSERT INTO LCS_PEOPLE (name, age, notes)
 VALUES ('Bob', 35, 'I like dogs')
/

INSERT INTO LCS_PEOPLE (name, age, notes)
 VALUES ('Kim', 27, 'I like birds')
/

INSERT INTO LCS_PETS (name, owner, type)
 VALUES ('Duke', 1, 'dog')
/

INSERT INTO LCS_PETS (name, owner, type)
 VALUES ('Pepe', 2, 'bird')
/

COMMIT
/
