FROM grafana/grafana-oss:latest
ADD ./datasources/*.yaml /etc/grafana/provisioning/datasources
#ADD ./datasources/*.json /etc/grafana/provisioning/datasources
ADD ./dashboards/*.yaml /etc/grafana/provisioning/dashboards
ADD ./dashboards/*.json /etc/grafana/provisioning/dashboards
