CREATE USER JDBCSP_USER IDENTIFIED BY <JDBCSP_USER_PASSWORD>;
GRANT DWROLE TO JDBCSP_USER;
GRANT CREATE SESSION TO JDBCSP_USER;
GRANT UNLIMITED TABLESPACE TO JDBCSP_USER;

CREATE TABLE EMPLOYEE
(
  "EMP_ID"   NUMBER NOT NULL ENABLE,
  "NAME"    VARCHAR2(20 BYTE) DEFAULT NULL,
  "ROLE"    VARCHAR2(20 BYTE) DEFAULT NULL,
  "DEPARTMENT"    VARCHAR2(20 BYTE) DEFAULT NULL,
  "BUILDING" VARCHAR2(20 BYTE) DEFAULT NULL,
  PRIMARY KEY ("EMP_ID")
);

CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE_PRC
(
 in_emp_id IN EMPLOYEE.EMP_ID%TYPE,
 in_name IN EMPLOYEE.NAME%TYPE,
 in_role IN EMPLOYEE.ROLE%TYPE,
 in_department IN EMPLOYEE.DEPARTMENT%TYPE,
 in_building IN EMPLOYEE.BUILDING%TYPE,
 out_result OUT VARCHAR2)
AS
BEGIN
  INSERT INTO EMPLOYEE (EMP_ID, NAME, ROLE, DEPARTMENT, BUILDING) 
  VALUES (in_emp_id, in_name, in_role, in_department, in_building);
  COMMIT;
  
  out_result := 'TRUE';
 
EXCEPTION
  WHEN OTHERS THEN 
  out_result := 'FALSE';
  ROLLBACK;
END;

GRANT EXECUTE ON INSERT_EMPLOYEE_PRC TO JDBCSP_USER;
