REM 
REM  Here we are going to force the following test query...
REM
REM      select /* HELLO */ num from bob where id = 100   (SQL ID 8c2dqym0cbqvj)
REM
REM  ...to stop using the BOB_PK index and use the BOB_IDX 
REM     index instead. This is just for demonstration purposes.
REM
REM  The plan we are taking, is generated by the following SQL statement:
REM
REM  SQL_ID  6fcg56sp87vvf, child number 0
REM
REM  select /* HELLO */ /*+ INDEX(bob bob_idx) */ num from bob where id = 100
REM
REM  Plan hash value: 4251244305
REM  -----------------------------------------------------------------------------------------------
REM  | Id  | Operation                           | Name    | Rows  | Bytes | Cost (%CPU)| Time     |
REM  -----------------------------------------------------------------------------------------------
REM  |   0 | SELECT STATEMENT                    |         |       |       |     3 (100)|          |
REM  |   1 |  TABLE ACCESS BY INDEX ROWID BATCHED| BOB     |     1 |     8 |     3   (0)| 00:00:01 |
REM  |*  2 |   INDEX RANGE SCAN                  | BOB_IDX |     1 |       |     2   (0)| 00:00:01 |
REM  -----------------------------------------------------------------------------------------------
REM 

@@fix_spm 8c2dqym0cbqvj 6fcg56sp87vvf 4251244305 fix force
