-- liquibase formatted sql

-- changeset liquibase:Initial
INSERT INTO SCHEMA_A.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (1, 'Engineering');
INSERT INTO SCHEMA_A.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (2, 'Sales');
INSERT INTO SCHEMA_A.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (3, 'HR');