{
 "title": "Cell Disk",
 "tags": [
  "celldisk",
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   },
   {
    "name": "celldiskType",
    "query": {
     "query": "{__name__=~\"CD_IO_RQ_R_SM_SEC|CD_IO_RQ_W_SM_SEC|CD_IO_RQ_R_LG_SEC|CD_IO_RQ_W_LG_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",objectName!~\"PM_.*\"}"
    }
   },
   { "name": "show", "label": "Show Latency", "query": "average : 15, max : 10" }
  ]
 },
 "panels": [
  {
   "title": "$celldiskType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "celldiskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Small Reads Requests",
     "type": "timeseries",
     "description": "EXAREL: Small read requests on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_R_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Write Requests",
     "type": "timeseries",
     "description": "EXAREL: Small write requests on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_W_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Read Requests",
     "type": "timeseries",
     "description": "EXAREL: Large read requests on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_R_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Write Requests",
     "type": "timeseries",
     "description": "EXAREL: Large write requests on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_W_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Read MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Small read MIB/s on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_R_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Smalll Write MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Small write MiB/s on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_W_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Read MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Large read MiB/s on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_R_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Write MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Large write MiB/s on devices\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_W_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Read Latency",
     "type": "timeseries",
     "description": "EXAREL: \nWhen using 'Show Latency': average, this shows the average small read latency on the devices.\n\nWhen using 'Show Latency': max, this shows the maximum small read latency over 1 minute windows on the devices\n\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_R_SM_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      },
      {
       "expr": "max_over_time(CD_IO_TM_R_SM_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}[1m]) BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 3 )",
       "legendFormat": "{{objectName}}-max"
      }
     ]
    },
    {
     "title": "Small Write Latency",
     "type": "timeseries",
     "description": "EXAREL: \nWhen using 'Show Latency': average, this shows the average small write latency on the devices.\n\nWhen using 'Show Latency': max, this shows the maximum small write latency over 1 minute windows on the devices\n\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_W_SM_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      },
      {
       "expr": "max_over_time(CD_IO_TM_W_SM_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}[1m]) BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 3 )",
       "legendFormat": "{{objectName}}-max"
      }
     ]
    },
    {
     "title": "Large Read Latency",
     "type": "timeseries",
     "description": "EXAREL: \nWhen using 'Show Latency': average, this shows the average large read latency on the devices.\n\nWhen using 'Show Latency': max, this shows the maximum large read latency over 1 minute windows on the devices\n\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_R_LG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      },
      {
       "expr": "max_over_time(CD_IO_TM_R_LG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}[1m]) BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 3 )",
       "legendFormat": "{{objectName}}-max"
      }
     ]
    },
    {
     "title": "Large Write Latency",
     "type": "timeseries",
     "description": "EXAREL: \nWhen using 'Show Latency': average, this shows the average large write latency on the devices.\n\nWhen using 'Show Latency': max, this shows the maximum large write latency over 1 minute windows on the devices\n\nFD: performance flash\nCD: hard disk\nCF: capacity flash",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_W_LG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      },
      {
       "expr": "max_over_time(CD_IO_TM_W_LG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}[1m]) BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 3 )",
       "legendFormat": "{{objectName}}-max"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrub Requests",
     "type": "timeseries",
     "description": "EXAREL: Scrub IO requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "CD_IO_RQ_R_SCRUB_SEC{objectName=~\"CD_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Scrub MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Scrub IO MiB/s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "CD_IO_BY_R_SCRUB_SEC{objectName=~\"CD_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Relocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Small Read Latency - Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "CD_IO_TM_R_SM_CLIENT_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Write Latency - Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "CD_IO_TM_W_SM_CLIENT_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Read Latency - Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "CD_IO_TM_R_LG_CLIENT_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Write Latency - Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "CD_IO_TM_W_LG_CLIENT_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Write Latency - Log Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "CD_IO_TM_W_SM_LOG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Write Latency - Log Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "CD_IO_TM_W_LG_LOG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"} BACKUP_20251024 BACKUP_20251030 EXPORT_20251209 backup_all.sh export_all.sh jq out.txt ( $show % 2 )",
       "legendFormat": "{{objectName}}"
      }
     ]
    }
   ]
  }
 ]
}