{
 "title": "Compute Server",
 "tags": [
  "compute",
  "server",
  "exadata",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fleet", "query": { "query": "label_values(DS_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(DS_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(DS_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(DS_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "EXAREL: CPU utilization",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DS_CPUT{server=~\"$server\"}",
     "legendFormat": "%CPU-{{server}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "EXAREL: Memory Utilization",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "constant": 6.5,
     "expr": "DS_MEMUT{server=~\"$server\"}",
     "legendFormat": "%Used-{{server}}"
    },
    {
     "expr": "DS_MEMUT_MS{server=~\"$server\"}",
     "legendFormat": "%MS-{{server}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Bytes - Client Network",
     "type": "timeseries",
     "description": "EXAREL: RX bytes/s on client Network",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_NET_RX_BY_SEC{server=~\"$server\",objectName=~\".*eth.*\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "RX Bytes - RDMA",
     "type": "timeseries",
     "description": "EXAREL: Network throughput",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "sum by(server) (EXW_ROCE_TX_BY_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-RoCE"
      },
      {
       "expr": "sum by(server) (N_IB_MB_RCV_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-IB"
      }
     ]
    },
    {
     "title": "TX Bytes - Client Network",
     "type": "timeseries",
     "description": "EXAREL: Tx bytes/s per interface",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_NET_TX_BY_SEC{server=~\"$server\",objectName=~\".*eth.*\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "TX Bytes - RDMA",
     "type": "timeseries",
     "description": "EXAREL: TX bytes on RDMA per interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (EXW_ROCE_TX_BY_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-RoCE"
      },
      {
       "expr": "sum by (server) (N_IB_MB_TRANS_SEC{server=~\"$server\"})",
       "legendFormat": "{{server}}-IB"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (objectName,server) ({__name__ =~\"OS_IO_RQ_R_SEC|OS_IO_RQ_W_SEC\", server=~\"$server\"})",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "sum by (objectName,server) ({__name__ =~\"OS_IO_BY_R_SEC|OS_IO_BY_W_SEC\", server=~\"$server\"})",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "r/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "OS_IO_RQ_R_SEC{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "w/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "OS_IO_RQ_W_SEC{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Read MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "OS_IO_BY_R_SEC{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Write MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "OS_IO_BY_W_SEC{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "OS_IO_UTIL_PCT{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "r_await",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "OS_IO_WT_R_RQ{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "w_await",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "OS_IO_WT_W_RQ{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}