{
 "title": "Disk IO",
 "tags": [
  "diskio",
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "server",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (CD_IO_RQ_R_SM_SEC{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Small Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_R_LG_SEC{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Large Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_W_SM_SEC{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Small Writes-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_W_LG_SEC{server=~\"$server\",objectName=~\"CD_.*\"})\n",
       "legendFormat": "Large Writes-{{server}}"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "FC_IO_RQ_R_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP misses-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Read Skips-{{server}}"
      },
      {
       "expr": "SIO_IO_RD_RQ_HD_SEC{server=~\"$server\"}",
       "legendFormat": "Smart Scans-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_RQ_R_SCRUB_SEC{server=~\"$server\",objectName=~\"CD_.*\"})",
       "legendFormat": "Scrub-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_W_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Write Skips-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_W_DISK_WRITER_SEC{server=~\"$server\"}",
       "legendFormat": "Disk Writer-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_MISS_DW_SEC{server=~\"$server\"}",
       "legendFormat": "DW misses-{{server}}"
      }
     ]
    },
    {
     "title": "MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (CD_IO_BY_R_SM_SEC{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Small Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_R_LG_SEC{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})\n",
       "legendFormat": "Large Reads-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_W_SM_SEC{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})\n",
       "legendFormat": "Small Writes-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_W_LG_SEC{server=~\"$server\",objectName=~\"CD_.*\"})\n",
       "legendFormat": "Large Writes-{{server}}"
      }
     ]
    },
    {
     "title": "Disk MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "FC_IO_BY_R_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP misses-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Read skips-{{server}}"
      },
      {
       "expr": "SIO_IO_RD_HD_SEC{server=~\"$server\"}",
       "legendFormat": "Smart Scan-{{server}}"
      },
      {
       "expr": "sum by (server) (CD_IO_BY_R_SCRUB_SEC{server=~\"$server\",objectName=~\"CD_.*\"})",
       "legendFormat": "Scrub-{{server}}"
      },
      {
       "expr": "FC_IO_BY_W_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Write Skips-{{server}}"
      },
      {
       "expr": "FC_IO_BY_W_DISK_WRITER_SEC{server=~\"$server\"}",
       "legendFormat": "Disk Writer-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_MISS_DW_SEC{server=~\"$server\"}",
       "legendFormat": "DW misses-{{server}}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (server) (CD_IO_TM_R_SM_RQ{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Small Reads-{{server}}"
      },
      {
       "expr": "avg by (server) (CD_IO_TM_R_LG_RQ{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Large Reads-{{server}}"
      },
      {
       "expr": "avg by (server) (CD_IO_TM_W_SM_RQ{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Small Writes-{{server}}"
      },
      {
       "expr": "avg by (server) (CD_IO_TM_W_LG_RQ{server=~\"$server\",objectName=~\"CD_.*|CF_.*\"})",
       "legendFormat": "Large Writes-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}