{
 "title": "Flash Cache",
 "tags": [
  "flashcache",
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Space Uitlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Space Utilization",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache space utilization",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "FC_BY_ALLOCATED{server=~\"$server\"}",
       "legendFormat": "Allocated-{{server}}"
      },
      {
       "expr": "FC_BY_ALLOCATED_OLTP{server=~\"$server\"}",
       "legendFormat": "OLTP-{{server}}"
      },
      {
       "expr": "FC_COL_BY_USED{server=~\"$server\"}",
       "legendFormat": "CC-{{server}}"
      },
      {
       "expr": "FC_BYKEEP_OLTP{server=~\"$server\"}",
       "legendFormat": "KEEP-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flash Cache IO Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flash Cache Hit%",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache Hit percentage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "100*FC_IO_RQ_R_SEC{server=~\"$server\"}/(FC_IO_RQ_R_SEC{server=~\"$server\"}+FC_IO_RQ_R_MISS_SEC{server=~\"$server\"}) > 0",
       "legendFormat": "%OLTP Hit-{{server}}"
      },
      {
       "expr": "100*FC_IO_RQ_R_DW_SEC{server=~\"$server\"}/(FC_IO_RQ_R_DW_SEC{server=~\"$server\"}+FC_IO_RQ_R_MISS_DW_SEC{server=\"$server\"}) > 0",
       "legendFormat": "%Scan Hit-{{server}}"
      },
      {
       "expr": "100*FC_COL_IO_BY_R_SEC{server=~\"$server\"}/FC_COL_IO_BY_R_ELIGIBLE_SEC{server=~\"$server\"} > 0",
       "legendFormat": "%CC Hit-{{server}}"
      },
      {
       "expr": "100*FC_IO_RQ_R_PROXYREAD_SEC{server=~\"$server\"}/(FC_IO_RQ_R_SEC{server=~\"$server\"}+FC_IO_RQ_R_MISS_SEC{server=~\"$server\"}) > 0",
       "legendFormat": "%Partner Hit-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache User Read Requests",
     "type": "timeseries",
     "description": "EXAREL: Flash cache user read requests",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "FC_IO_RQ_R_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP Hits-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP Misses-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Skips-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan Hits-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_MISS_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan Misses-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_PROXYREAD_SEC{server=~\"$server\"}",
       "legendFormat": "PartnerRead Hits-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_PROXYREAD_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "PartnerRead Misses-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache User Write Requests",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache user write requests",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "FC_IO_RQ_W_SEC{server=~\"$server\"}",
       "legendFormat": "Writes-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_W_FIRST_SEC{server=~\"$server\"}",
       "legendFormat": "First Writes-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_W_OVERWRITE_SEC{server=~\"$server\"}",
       "legendFormat": "Overwrites-{{$server}}"
      },
      {
       "expr": "FC_IO_RQ_W_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Skips-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache Disk Writer Requests",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache disk writer IO requests",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "FC_IO_RQ_W_DISK_WRITER_SEC{server=~\"$server\"}",
       "legendFormat": "Writes-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_R_DISK_WRITER_SEC{server=~\"$server\"}",
       "legendFormat": "Reads-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache Internal Write Requests",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache internal write requests",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "FC_IO_RQ_W_POPULATE_SEC{server=~\"$server\"}",
       "legendFormat": "Population-{{server}}"
      },
      {
       "expr": "FC_IO_RQ_W_METADATA_SEC{server=~\"$server\"}",
       "legendFormat": "Metadata-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache User Read MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache user read MiB/s",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FC_IO_BY_R_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP Hits-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_MISS_SEC{server=~\"$server\"}",
       "legendFormat": "OLTP Misses-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan Hits-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_MISS_DW_SEC{server=~\"$server\"}",
       "legendFormat": "Scan Misses-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Skips-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache User Writes MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache user write MiB/s",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FC_IO_BY_W_SEC{server=~\"$server\"}",
       "legendFormat": "Writes-{{server}}"
      },
      {
       "expr": "FC_IO_BY_W_FIRST_SEC{server=~\"$server\"}",
       "legendFormat": "First Writes-{{server}}"
      },
      {
       "expr": "FC_IO_BY_W_OVERWRITE_SEC{server=~\"$server\"}",
       "legendFormat": "Overwrites-{{server}}"
      },
      {
       "expr": "FC_IO_BY_W_SKIP_SEC{server=~\"$server\"}",
       "legendFormat": "Skips-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache Disk Writer MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache disk writer IO MiB/s",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FC_IO_BY_W_DISK_WRITER_SEC{server=~\"$server\"}",
       "legendFormat": "Writes-{{server}}"
      },
      {
       "expr": "FC_IO_BY_R_DISK_WRITER_SEC{server=~\"$server\"}",
       "legendFormat": "Reads-{{server}}"
      }
     ]
    },
    {
     "title": "Flash Cache Internal Write MiB/s",
     "type": "timeseries",
     "description": "EXAREL: Flash Cache internal write MiB/s",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "FC_IO_BY_W_POPULATE_SEC{server=~\"$server\"}",
       "legendFormat": "Population-{{server}}"
      },
      {
       "expr": "FC_IO_BY_W_METADATA_SEC{server=~\"$server\"}",
       "legendFormat": "Metadata-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}