{
 "title": "IO Profile",
 "tags": [
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   },
   {
    "name": "celldiskType",
    "query": {
     "query": "{__name__=~\"CD_IO_RQ_R_SM_SEC|CD_IO_RQ_W_SM_SEC|CD_IO_RQ_R_LG_SEC|CD_IO_RQ_W_LG_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",server=~\"$server\",objectName!~\"PM_.*\"}"
    }
   },
   {
    "name": "diskType",
    "query": {
     "query": "{__name__ =~ \"OS_IO_RQ_R_SEC|OS_IO_RQ_R_W_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",server=~\"$server\",objectName=~\"sd.*|nv.*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IO Latency - ${diskType}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "diskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "r_await",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_IO_WT_R_RQ{objectName=~\"${diskType}.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "w_await",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_IO_WT_W_RQ{objectName=~\"${diskType}.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Latency - ${celldiskType}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "celldiskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Small Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_R_SM_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_W_SM_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_R_LG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_TM_W_LG_RQ{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IOPs - ${diskType}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "diskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "r/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_IO_RQ_R_SEC{objectName=~\"${diskType}.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "w/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_IO_RQ_W_SEC{objectName=~\"${diskType}.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IOPs - ${celldiskType}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "celldiskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Small Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_R_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_W_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_R_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_RQ_W_LG_SEC{objectName=~\"${celldiskType}_.*\", server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Throughput - ${diskType}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "diskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_IO_BY_R_SEC{objectName=~\"${diskType}.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "Write MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "OS_IO_BY_W_SEC{objectName=~\"${diskType}.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Throughput - ${celldiskType}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "celldiskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Small Read MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_R_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Small Write MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_W_SM_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Read MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_R_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    },
    {
     "title": "Large Write MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CD_IO_BY_W_LG_SEC{objectName=~\"${celldiskType}_.*\",server=~\"$server\"}",
       "legendFormat": "{{objectName}}"
      }
     ]
    }
   ]
  }
 ]
}