{
 "title": "IO Statistics (Aggr)",
 "description": "IO Statistics",
 "tags": [
  "iostat",
  "exadata",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   },
   {
    "name": "diskType",
    "query": {
     "query": "query_result(label_replace(label_replace({__name__=~\"OS_IO_RQ_R_SEC|OS_IO_W_R_SEC\",fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\",server=~\"$server\"},\"diskType\",\"${1}\",\"objectName\",\"(.*):.*\"),\"diskType\",\"$1\",\"objectName\",\"([a-z][a-z])[^:]*\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$diskType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "diskType",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IOPs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) ({__name__ =~\"OS_IO_RQ_R_SEC|OS_IO_RQ_W_SEC\", server=~\"$server\", objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}-$diskType"
      }
     ]
    },
    {
     "title": "MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) ({__name__ =~\"OS_IO_BY_R_SEC|OS_IO_BY_W_SEC\", server=~\"$server\", objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "r/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (OS_IO_RQ_R_SEC{server=~\"$server\", objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "w/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (OS_IO_RQ_W_SEC{server=~\"$server\",objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Read MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (OS_IO_BY_R_SEC{server=~\"$server\",objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Write MiB/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "sum by (server) (OS_IO_BY_W_SEC{server=~\"$server\",objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "avg by (server) (OS_IO_UTIL_PCT{server=~\"$server\", objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "r_await",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "avg by (server) (OS_IO_WT_R_RQ{server=~\"$server\",objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "w_await",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "avg by (server) (OS_IO_WT_W_RQ{server=~\"$server\",objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "aqu-sz",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "avg by (server) (OS_IO_AQU_SZ{server=~\"$server\",objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "rareq-sz",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "avg by (server) (OS_IO_RQ_R_SZ{server=~\"$server\", objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "wareq-sz",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "avg by (server) (OS_IO_RQ_W_SZ{server=~\"$server\", objectName=~\"${diskType}.*\"})",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  }
 ]
}