{
 "title": "Smart Scan",
 "tags": [
  "exadata",
  "storage",
  "smartscan",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   { "name": "fleet", "query": { "query": "label_values(CL_CPUT,fleet)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(CL_CPUT{fleet=\"$fleet\",pod=\"$pod\",cluster=~\"$cluster\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "EXAREL: cpu utilization on the cells",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "CL_CPUT{server=~\"$server\"}",
       "legendFormat": "%cell cpu-{{server}}"
      },
      {
       "expr": "CL_CPUT_CS{server=~\"$server\"}",
       "legendFormat": "%cellsrv cpu-{{server}}"
      }
     ]
    },
    {
     "title": "Smart IO CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "us/s" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "SIO_FG_CPU_SEC{server=~\"$server\"}",
       "legendFormat": "Foreground CPU-{{server}}"
      },
      {
       "expr": "SIO_BG_CPU_SEC{server=~\"$server\"}",
       "legendFormat": "Background CPU-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Available",
     "type": "timeseries",
     "description": "EXAREL: %memory utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_CELLMEM_OS_AVAIL_PCT{server=~\"$server\"}",
       "legendFormat": "%OS available-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_CELL_AVAIL_PCT{server=~\"$server\"}",
       "legendFormat": "%cellsrv available-{{server}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "EXAREL: Memory Usagse",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_CELLMEM_OS_TOTAL{server=~\"$server\"}",
       "legendFormat": "Total-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_OS_KNL{server=~\"$server\"}",
       "legendFormat": "OS kernel-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_OS_USR{server=~\"$server\"}",
       "legendFormat": "OS user-{{server}}"
      }
     ]
    },
    {
     "title": "Cellsrv Memory",
     "type": "timeseries",
     "description": "EXAREL: cellsrv memory usage",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "repeat": "server",
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_CELLMEM_CELL_CELLSRV{server=~\"$server\"}",
       "legendFormat": "cellsrv-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_CELL_OFFLOAD{server=~\"$server\"}",
       "legendFormat": "offload-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_CELL_KNL{server=~\"$server\"}",
       "legendFormat": "kernel-{{server}}"
      },
      {
       "expr": "EXW_CELLMEM_OTHER_SERV{server=~\"$server\"}",
       "legendFormat": "other services-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}