SELECT * FROM V$VERSION;

CREATE USER VECTOR_USER IDENTIFIED BY <YOUR_PASSWORD> QUOTA UNLIMITED ON USERS;
GRANT DB_DEVELOPER_ROLE TO VECTOR_USER;
GRANT CREATE SESSION TO VECTOR_USER;

GRANT SELECT ANY TABLE ON SCHEMA VECTOR_USER TO VECTOR_USER;
GRANT SELECT ANY TABLE ON SCHEMA VECTOR_USER TO VECTOR_USER;
GRANT SELECT ANY TABLE ON SCHEMA VECTOR_USER TO VECTOR_USER;
GRANT SELECT ANY TABLE ON SCHEMA VECTOR_USER TO VECTOR_USER;

ALTER SESSION SET CURRENT_SCHEMA = VECTOR_USER;

CREATE TABLE VECTOR_USER.ORACLE_AI_VECTOR_SEARCH_DEMO (ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY, VECTOR_DATA VECTOR(3, FLOAT64));
COMMIT;

DESCRIBE VECTOR_USER.ORACLE_AI_VECTOR_SEARCH_DEMO;

SELECT * FROM VECTOR_USER.ORACLE_AI_VECTOR_SEARCH_DEMO;

DELETE FROM VECTOR_USER.ORACLE_AI_VECTOR_SEARCH_DEMO;
COMMIT;

DROP TABLE VECTOR_USER.ORACLE_AI_VECTOR_SEARCH_DEMO PURGE; 





